variables:
    javaVersion: 21

stages:
    - stage: BuildStage
      displayName: BuildStage
      pool:
          vmImage: "ubuntu-latest"
      jobs:
          - job: BuildJob
            steps:
                - script: echo "This is a test message from the build stage."
                  displayName: Echo Test Message
                - bash: chmod +x ./gradlew
                  displayName: "Grant execute permission to gradlew"
                - script: ./gradlew --version
                  displayName: Print out Gradle version
                - task: Gradle@3
                  displayName: Gradle Clean Build
                  inputs:
                      gradleWrapperFile: "gradlew"
                      options: "--info --stacktrace"
                      tasks: "clean build"
                  env:
                      JAVA_OPTS: "-Xmx3072m"
                - bash: |
                      echo "Searching for TEST reports..."
                      find . -name 'TEST-*.xml'
                  displayName: "Debug: Locate test report files"
                - task: PublishTestResults@2
                  displayName: "Publish JUnit Test Results"
                  condition: succeededOrFailed()
                  inputs:
                      testResultsFormat: "JUnit"
                      testResultsFiles: "**/build/test-results/test/TEST-*.xml"
                      failTaskOnMissingResultsFile: false
