/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datastructure;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

final class SingleLinkedListTest {
    @Test
    void testConstructor() {
        SingleLinkedList list = new SingleLinkedList();
        assertEquals(0, list.size());
    }

    @Test
    void testAdd() {
        SingleLinkedList list = new SingleLinkedList();
        list.add("one");
        assertEquals(1, list.size());
        assertEquals("one", list.get(0));

        list.add("two");
        assertEquals(2, list.size());
        assertEquals("two", list.get(1));
    }

    @Test
    void testRemove() {
        SingleLinkedList list = new SingleLinkedList();
        list.add("one");
        list.add("two");

        assertTrue(list.remove("one"));
        assertEquals(1, list.size());
        assertEquals("two", list.get(0));
        assertTrue(list.remove("two"));
        assertEquals(0, list.size());
    }

    @Test
    void testRemoveMissing() {
        SingleLinkedList list = new SingleLinkedList();

        list.add("one");
        list.add("two");
        assertFalse(list.remove("three"));
        assertEquals(2, list.size());
    }
}
